version: '3'
services:
  otel-collector:
    image: otel/opentelemetry-collector
    volumes:
      - ./otel-collector-cnfig.yaml:/otel-collector-cnfig.yaml
    command: ["--config=/otel-collector-cnfig.yaml"]
    ports:
      - 4317:4317
    depends_on:
      - zipkin
      - jaeger
      - prometheus
      - kafka

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
      - "9000:9000"

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"
      - "14268:14268"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  kafka:
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - 2181:2181

