services:
        
#  otel-collector:
#    image: otel/opentelemetry-collector-contrib
#    command: [--config=/etc/otel-collector-config.yaml]
#    volumes:
#      - /d/VMs/podman/otel/otel-local-config.yaml:/etc/otel-collector-config.yaml
#    ports:
#      - 1888:1888 # pprof extension
#      - 8888:8888 # Prometheus' metrics exposed by the collector
#      - 8889:8889 # Prometheus exporter metrics
#      - 13133:13133 # health_check extension
#      - 4312:4317 # OTLP gRPC receiver
#      - 4318:4318 # OTLP http receiver
#      - 55679:55679 # zpages extension
#    
  zookeeper:
    image: ubuntu/zookeeper:edge
    container_name: zookeeper
    #    volumes:
    #      - /mnt/MX500/AppData/kafka:/etc/kafka
    ports:
      - 2181:2181
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    network_mode: bridge
      
      

  kafka:
    image: ubuntu/kafka:latest
    container_name: kafka
    environment:
      - ZOOKEEPER_HOST=192.168.0.171
      - ZOOKEEPER_PORT=2181
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
    ports:
      - 9092:9092
  #    volumes:
  #      - /mnt/MX500/AppData/kafka:/etc/kafka

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8246:8080
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
    volumes:
      - /d/VMs/podman/kafka-ui/config.yml:/etc/kafkaui/config.yml