services:
  
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib
    command: [--config=/etc/otel-collector-config.yaml]
    volumes:
      - ./otel/otel-local-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - 4317:4317
    depends_on:
      - zipkin
      - jaeger
      - kafka

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - local

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one
    ports:
      - 16686:16686
      - 14268:14268
    networks:
      - local
    


  zookeeper:
    image: ubuntu/zookeeper:edge
    container_name: zookeeper
    #    volumes:
    #      - /mnt/MX500/AppData/kafka:/etc/kafka
    ports:
      - 2181:2181
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    networks:
      - local
  
  
  kafka:
    image: ubuntu/kafka:latest
    container_name: kafka
    environment:
      - ZOOKEEPER_HOST=192.168.0.171
      - ZOOKEEPER_PORT=2181
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
    ports:
      - 9092:9092
    networks:
      - local
  #    volumes:
  #      - /mnt/MX500/AppData/kafka:/etc/kafka

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8246:8080
    networks:
      - local
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
    volumes:
      - /Users/jamal/docker/kafka-ui/config.yaml:/etc/kafkaui/config.yml
 
networks:
    local:
      driver: bridge