# /tmp/otel-collector-config.yaml
receivers:
  otlp:
    protocols:
      http:
      grpc:
        
exporters:
  logging:
    loglevel: debug
    
  jaeger:
    endpoint: http://localhost:14250
  
  zipkin:
      endpoint: localhost:9411/api/v2/spans # Replace with your Zipkin endpoint URL
  
  prometheus:
    endpoint: prometheus:8889
    namespace: default
    
    
    
processors:
  batch:
    
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging,jaeger,zipkin]
      processors: [batch]
    metrics:
      receivers: [otlp]
      exporters: [logging]
      processors: [batch]
